### ISSUE TITLE
Revamp the enquiry form

### ISSUE THREAD

**Issue by royuen** [oursky/oursky-web#103]
- [x] Change "Hello" to "Get in touch"
- [x] Change "Fill in the form below to reach us" to "Got a project you're excited about and think we can help?"
- [x] Remove "which of the following services do you need" and "Project Name"
- [x] Change "Contact Person" to "Name"
- [x] Change "Phone" to "Phone No."
- [x] Add "Company" after Contact Person and required
- [x] Change "Project Summary" to "How Can We Help?"
- [x] Remove "Any documents for us to go through"

---

Also need to create a backend API
- [ ] Send an email to "inbound@oursky.com" after the form is submitted.

**Comment by hochiw** [comment]
@royuen I noticed that the enquiry form is currently using PandaForm, do you by any chance have an access to it that can be shared to me to have a look and see if the email sending part can be done there or not?

**Comment by royuen** [comment]
We will use zapier for that. Let me share the info to you later @hochiw

**Comment by hochiw** [comment]
thanks

**Comment by royuen** [comment]
@Rico-Wong please follow here - https://3.basecamp.com/3096882/buckets/12067974/todos/2934572948 access granted

**Comment by hochiw** [comment]
Thanks!
