### ISSUE TITLE
In page images are broken

### ISSUE THREAD

**Issue by royuen** [oursky/oursky-web#112]
For example
https://oursky2020.netlify.app/product-development
https://oursky2020.netlify.app/mobile
and other pages too:

![Screenshot 2020-08-28 at 10.37.08 PM.png](https://zube.io/files/oursky/6753863c1aa1f6b83615a74a4b283877-screenshot-2020-08-28-at-10-37-08-pm.png)

**Comment by hochiw** [comment]
hmm seems like the convert script only works on part of the website. Maybe I will just convert the images myself and use <picture> tag to serve both webp and the original format in case the browser doesn't load.
