### ISSUE TITLE
Add google structure data format

### ISSUE THREAD

**Issue by royuen** [oursky/oursky-web#129]
- [ ] All pages - https://developers.google.com/search/docs/data-types/breadcrumb
- [ ] Home - https://developers.google.com/search/docs/data-types/local-business
- [ ] Home - https://developers.google.com/search/docs/data-types/logo

**Comment by royuen** [comment]
@Rico-Wong 

https://search.google.com/structured-data/testing-tool/u/0/#url=oursky.com

![Screenshot 2020-09-02 at 1.34.39 PM.png](https://zube.io/files/oursky/df9f40499b0bebb597c034e33606f344-screenshot-2020-09-02-at-1-34-39-pm.png)

**Comment by hochiw** [comment]
sorry, pushed a fix :adore2x:

**Comment by royuen** [comment]
Fix warning:
- [ ] https://search.google.com/structured-data/testing-tool/u/0/

**Comment by hochiw** [comment]
oh i've been using https://search.google.com/test/rich-results as they are deprecating the structured data testing tool, shall I modify it to pass the old one instead?

**Comment by royuen** [comment]
Oh no need then. Let me review
