### ISSUE TITLE
Redirect oursky to www.oursky.com instead

### ISSUE THREAD

**Issue by chpapa** [oursky/oursky-web#131]
For SEO purpose.

And set canonical UR:

<meta property=”og:url” content=”http://www.oursky.com” />

**Comment by hochiw** [comment]
I've send in a PR for the canonical urls as I assume the rest will be handled in route 53 which I don't have access to.

**Comment by royuen** [comment]
@rickmak can you help review and update too? Thanks!

**Comment by chpapa** [comment]
I made the changes.

**Comment by hochiw** [comment]
Thanks 🙏
