### ISSUE TITLE
[Mobile, Service enquiry] Incorrect font size of some texts in the thank-you message after submitting enquiries

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#137]
Build: Production
Device: Safari on iPad 7th gen (13.6.1), Galaxy s20+ (10.0)

Step:
1. Go to the 'Service enquiry' page in mobile view and in desktop view
2. Submit an enquiry
3. See the font size of 'Thank you' is not larger than that of other characters in the mobile view

Screenshots:
![IMG-0522](https://user-images.githubusercontent.com/67095825/91832298-d199c380-ec77-11ea-945e-8802517fed29.PNG)
![Screenshot_20200901-161534_Samsung Internet](https://user-images.githubusercontent.com/67095825/91832303-d3638700-ec77-11ea-800d-ccefe6a308ad.jpg)

**Comment by JasonNS1425** [comment]
Can still reproduce on staging and production

**Comment by hochiw** [comment]
Not yet merged
