### ISSUE TITLE
[Assests] Missing favicon on 'assets' pages

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#138]
Build: Staging
Device: Chrome on win 10

Step:
1. Go to the 'Microservices and Containerization' page
2. Scroll down 'Exploring cloud-native app...' section and click 'Download now'
3. See the opened page under 'oursky.com' domain does not have favicon

Screenshot:
![image](https://user-images.githubusercontent.com/67095825/91835428-f4c67200-ec7b-11ea-9fdf-08f22eeb682b.png)

**Comment by hochiw** [comment]
I've added a rerouting rule to the s3 bucket that exposes the favicon to the root path, and have confirmed that it's working via the [aws link](http://oursky.com.s3-website-us-west-2.amazonaws.com/assets/skygear-wp-microservices.pdf), maybe it will take some time for oursky.com to update

**Comment by JasonNS1425** [comment]
Can still reproduce the issue.

**Comment by hochiw** [comment]
forgot to update this. I suppose pdf viewers natively don't have a configuration for favicons, as a workaround I tried using site-wide favicon, it doesn't seem to work on the custom domain `oursky.com` but works on the aws domain. @@ let's move the favicon to the root and see if it works.
