### ISSUE TITLE
[iPad Safari, General] Navigation menu is closed upon returning to the browser from other apps

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#139]
Build: Production
Device: iPad 7th gen (13.6.1)

Step:
1. Open the navigation menu in iPad devices
2. Switch to another app
3. Return to the browser and see the menu is closed

Screenshots:
https://drive.google.com/file/d/1GoxZQSPNHyJn-rssdkuWC0CgwDXq1O-1/view?usp=sharing

**Comment by JasonNS1425** [comment]
Can still reproduce on Staging and production

**Comment by hochiw** [comment]
oh not yet merged, I will move back to in progress

**Comment by JasonNS1425** [comment]
@royuen @hochiw Can still reproduce the issue. Is the merge deployed yet?

**Comment by hochiw** [comment]
yes it's deployed and yes it's still reproducible ( i tested it so many times in the process 🤦&zwj;♂️ )
