### ISSUE TITLE
[Mobile, About Us] Inconsistent behavior of some 'About Us' button in the navigation menu/header

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#140]
Build: Production
Device: iPad 7th gen (13.6.1)

Step:
1. Open the website in desktop view and in mobile view
2. Activate the navigation header/menu
3. Click the 'About us' button on the category and under the 'About Us' category, see the following behavior:
- Desktop, 'About us' category button: Go to the 'about us' page
- Desktop, 'About Us' button under category: Go to the 'about us' page
- Mobile, 'About Us' category button: No response
- Mobile, 'About Us' button under category: Go to the 'about us' page

Screenshots:
https://drive.google.com/file/d/1DIVskG2mDNanHVtNjrU3cbq7M6ObNapp/view?usp=sharing

**Comment by hochiw** [comment]
i will disable the category button
