### ISSUE TITLE
Update About us content

### ISSUE THREAD

**Issue by royuen** [oursky/oursky-web#18]
About us section and its content from https://docs.google.com/document/d/1VQELlU48ignmGdwXs9epcpfMOZtV2OQDUnql2vNZYrU/edit

About us - https://docs.google.com/document/d/1rE3kHr3v02oKBoGaRiAQc27Ngff0ovN_S0CTNw_p01k/edit
Our Technology Stack - https://docs.google.com/document/d/19IrJ-EVWBO_dATRW-OllSDQBhh9YjIfyfsZiKP7tKeE/edit

**Comment by hochiw** [comment]
Missing introduction from Ten and Joyz 😂 I will add the entries but comment them out first
