### ISSUE TITLE
CICD to S3 & Cloudfront

### ISSUE THREAD

**Issue by royuen** [oursky/oursky-web#19]
- [x] Push code to production branch shall auto deploy to target S3 bucket
- [x] Update oursky.com cloudfront to point to oursky.com (only when all changes are confirmed)

**Comment by rickmak** [comment]
I create an IAM with s3 permission restricted to oursky.com s3 us-west-2 bucket and cf-invaliation. The AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and CDN_DISTRIBUTION_ID are set as project secret.

Please setup the Github Action for production branch for push and deploy.
