### ISSUE TITLE
Update missing icons

### ISSUE THREAD

**Issue by hochiw** [oursky/oursky-web#23]
Homepage
- UI/UX and Digital Product Design row in Service List
![image.png](https://zube.io/files/oursky/38a4033552a717b189ee6c6993253a10-image.png)
- Products in product list after [oursky/oursky-web#15 (oursky/oursky-web#15)](https://zube.io/oursky/oursky-website/c/15) 
![image.png](https://zube.io/files/oursky/1a38b0419287cc0519fd86b0da2e1d64-image.png)

Case Studies
- Musicmap gif banner 
![image.png](https://zube.io/files/oursky/ba773760b430153b85bdd9f474119027-image.png)

Case Studies/Snaptee
- Snaptee banner
![image.png](https://zube.io/files/oursky/6992c47fdb1308861af36874a822925d-image.png)

Case Studies/HL Insurance
- HL Insurance banner
![image.png](https://zube.io/files/oursky/f23195efdc6cca59a1f8aafd79dc057d-image.png)

Case Studies/MusicMap
- MusicMap banner
![image.png](https://zube.io/files/oursky/94f41389c88dffb55741d5ec89620e7c-image.png)

Case Studies/Wilson Parking
- Wilson Parking banner
![image.png](https://zube.io/files/oursky/f6cfd0706a23a0443c9b1fe519d7dbf5-image.png)

Microservices
- Helm logo
- Github Runner logo
- Travis logo
- Github actions logo
![image.png](https://zube.io/files/oursky/394a4a55dbf795ab62ccade4cc019b7b-image.png)

Products
https://oursky2020.netlify.app/mobile

Shall make these 2 images brighter?

![Screenshot 2020-08-26 at 11.01.54 PM.png](https://zube.io/files/oursky/a7303ab1a3bed17dd8d8fa27e7104d5a-screenshot-2020-08-26-at-11-01-54-pm.png)

Tech Page
<img width="471" alt="Screenshot 2020-08-27 at 1 11 33 PM" src="https://user-images.githubusercontent.com/18374475/91387009-d5d47400-e866-11ea-82a7-d686e012159c.png">

**Comment by koskosm** [comment]
@koskosm will provide assets this week

**Comment by royuen** [comment]
UI UX icon - https://www.dropbox.com/s/xzodlmcnv5dtob7/oursky-logo--playground.png?dl=0

**Comment by koskosm** [comment]
@royuen @hochiw I will add missing images overnight tonight.
