### ISSUE TITLE
about-us: Update missing introductions

### ISSUE THREAD

**Issue by hochiw** [oursky/oursky-web#47]
not yet available at the moment
https://docs.google.com/document/d/1rE3kHr3v02oKBoGaRiAQc27Ngff0ovN_S0CTNw_p01k/edit#

**Comment by royuen** [comment]
@Rico-Wong is that because no design? or why missed?

**Comment by hochiw** [comment]
@royuen we have the names but we don't have the content in the document.

**Comment by royuen** [comment]
Oh i see!

Will ask

And can you add "About us" within the sub-menu too above the "Our technology stack"? I totally missed @@

**Comment by hochiw** [comment]
sure
