### ISSUE TITLE
Fix title alignment

### ISSUE THREAD

**Issue by royuen** [oursky/oursky-web#75]
Let's align the title for iOS section

https://oursky2020.netlify.app/mobile
![Screenshot 2020-08-26 at 11.06.12 PM.png](https://zube.io/files/oursky/9b9dfcd15381ecd68351a52b728640ca-screenshot-2020-08-26-at-11-06-12-pm.png)

https://oursky2020.netlify.app/web
![Screenshot 2020-08-26 at 11.08.32 PM.png](https://zube.io/files/oursky/9d49b1bb7e4f9b48aa4adc4ec4cbd637-screenshot-2020-08-26-at-11-08-32-pm.png)

https://oursky2020.netlify.app/design
![Screenshot 2020-08-26 at 11.09.28 PM.png](https://zube.io/files/oursky/67ec013debcfcc2f21128b089650037c-screenshot-2020-08-26-at-11-09-28-pm.png)

https://oursky2020.netlify.app/microservice
![Screenshot 2020-08-26 at 11.11.21 PM.png](https://zube.io/files/oursky/4f27ccc11607f764b647e91b053d0a04-screenshot-2020-08-26-at-11-11-21-pm.png)

**Comment by hochiw** [comment]
potential fix: https://codepen.io/Chiffie/pen/EdaEpW

**Comment by hochiw** [comment]
Tried different approaches that seems like separating heading and content into two groups work the best. While it works on desktop browsers, the layout breaks when it comes to smaller devices. so worst case we would need two different layouts for the same contents. Will continue trying.

**Comment by koskosm** [comment]
@hochiw for this foundation framework has a plugin tool called equalizer:

https://get.foundation/sites/docs/equalizer.html

Add the data attribute to the dom element and it will make them equal height, and also can specify it for medium screen size only.

**Comment by hochiw** [comment]
damn that helps a lot :adore2x:
