### ISSUE TITLE
[Tech stack] Turn the tech stack image to html

### ISSUE THREAD

**Issue by royuen** [oursky/oursky-web#77]
https://oursky2020.netlify.app/tech

- Change the current image to html, and having logos displayed individually
- In mobile view, display it in one column

**Comment by koskosm** [comment]
![6779049D-F6A7-4F71-81AB-28E689C61D0B](https://user-images.githubusercontent.com/1007928/91382512-7cffde00-e85c-11ea-98e2-33ff79666482.png)


@hochiw you can use the existing layout for development page 

cc @royuen
