### ISSUE TITLE
[Product developments] Missing exact client name in some paragraphs

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#87]
Build: Staging
Device: Chrome on win 10

Step:
1. Go to the 'Product Developments' page
2. Scroll to the 'What we do' section > 'Cross-Platform App Development' part
3. See the 'Learn more through [client name]...' message

Screenshot:
![image](https://user-images.githubusercontent.com/67095825/91433070-472b1b80-e895-11ea-8101-cffcc6dd0aae.png)

**Comment by royuen** [comment]
Let's remove that "Learn more..." sentence first
