### ISSUE TITLE
[Homepage] Missing hyperlink for the 'Digital Product Development' quick-link button

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#89]
Build: Staging
Device: Chrome on win 10

Step:
1. Go to the homepage and scroll to the 'Digital transformation powered by...' part
2. Click the 'Digitial Product Development' and see no response

Screenshot:
![image](https://user-images.githubusercontent.com/67095825/91433798-65dde200-e896-11ea-9652-db149556a912.png)

**Comment by royuen** [comment]
Please point to https://oursky2020.netlify.app/product-development instead

**Comment by hochiw** [comment]
we might need a workaround for the nested links as they are not a html standard.
