### ISSUE TITLE
[Mobile] Should not be able to interact with the back layer when the navigation menu is active

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#93]
Build: Staging
Device: iPhone 6s+ (13.5.1), Nokia 8.1 (10)

Step:
1. Open the navigation menu in the mobile view
2. Try scrolling the page at some blank area
3. See the page at the back layer is scrolled

Screenshots:
https://drive.google.com/file/d/1bvqvHl6onPtCJ6WAYD5gpKOY8wmcYJHH/view?usp=sharing

**Comment by JasonNS1425** [comment]
The issue is no longer found in Safari. However, in the Samsung native browser, the body can easily be scrolled when the menu is opened, and by doing so the menu will be closed instantly. This causes great inconvenience to the users who attempt to scroll the navigation menu.

**Comment by royuen** [comment]
@Rico-Wong please help

**Comment by hochiw** [comment]
hmm the body in fact doesn't get scrolled, it seems like the fix to oursky/oursky-web#88 in which the menu gets dismissed when the browser is resized gets triggered by the samsung native browser as it resizes its window to make room for the toolbars when we scroll

**Comment by JasonNS1425** [comment]
Can still reproduce the issue
