### ISSUE TITLE
[Navigation footer, Safari Mobile] Will not open mail draft window upon tapping on oursky email

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#95]
Build: Staging
Device: iPad 7th gen (13.6), iPhone 6s+ (13.5.1)

Step:
1. Open the website in Safari Mobile
2. Scroll to the footer and click the oursky email
3. See the 'Work with us' page is opened instead of the mail draft window

Screenshots:
https://drive.google.com/file/d/1UjawlznnMM2N9Q7qabY2brzR-7h0u1AK/view?usp=sharing

**Comment by royuen** [comment]
@chpapa Right now at the bottom left corner, we have the email, do u want us to put the email directly, or just to remove it or changing to something else?

**Comment by chpapa** [comment]
Have an email directly is fine too.

**Comment by royuen** [comment]
noted

**Comment by hochiw** [comment]
The url is correctly set, it's just that the mobile menu is somehow blocking the footer on safari even though it's not visible.
