### ISSUE TITLE
[Mobile, Navigation menu] Close button of the menu can hardly be viewed at some positions

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#96]
Build: Staging
Device: Safari on iPhone 6s+ (13.5.1), Samsung native browser on Nokia 8.1 (10)

Step:
1. Open the website using mobile devices
2. Scroll down and open the navigation menu (e.g. the 'low-code solutions...' part on the homepage)
3. See the close button can hardly be viewed at some positions

Screenshot:
https://drive.google.com/file/d/14CsjUEOsIqGAOOuEwaKennjvKJ-klh1v/view?usp=sharing

**Comment by hochiw** [comment]
Shouldn't be able to scroll the body when the menu is opened.

**Comment by JasonNS1425** [comment]
@hochiw The issue still exists. Seems that my 'steps to reproduce' is not clear enough and caused some misunderstandings @@... Will update the description now.
![IMG-0523](https://user-images.githubusercontent.com/67095825/91831066-2dfbe380-ec76-11ea-9914-f43029e21f3f.jpg)
