### ISSUE TITLE
[Mobile, Navigation menu] Inconsistency of navigation menu options in web and mobile

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#98]
Build: Staging
Device: Chrome on win 10, iPhone 6s+ (13.5.1)

Step:
1. Open the website in desktop/mobile devices
2. Open the navigation menu in mobile devices, compare with the options of navigation header in web
3. See the following differences:
- the titles of the navigators under the tab 'Services' are different
- 'Work with us' vs 'Start your project'
- Missing 'about us' option under 'about us' tab

Screenshots:
![image](https://user-images.githubusercontent.com/67095825/91439019-eb659000-e89e-11ea-9a25-2e707f7e0925.png)
![image](https://user-images.githubusercontent.com/67095825/91439041-f4566180-e89e-11ea-8431-f622ba86ab89.png)
![Screenshot_20200827-195232](https://user-images.githubusercontent.com/67095825/91439079-01735080-e89f-11ea-8cf0-ae9a0476b470.png)

**Comment by JasonNS1425** [comment]
@royuen Under the 'Services' tab, the navigator 'Microservices and Containerization' is still displayed as 'Microservices Development' in the mobile view. Is it the expected mobile design? @@

**Comment by royuen** [comment]
@Rico-Wong please follow desktop
