### ISSUE TITLE
[Mobile, Navigation menu] Navigator text overlapped with 'OurSky Logo' upon scrolling

### ISSUE THREAD

**Issue by JasonNS1425** [oursky/oursky-web#99]
Build: Staging
Device: Nokia 8.1 (10), iPhone 6s+ (13.5.1)

Step:
1. Open the navigation menu and scroll the menu down
2. See the overlapping text

Screenshots:
![Oursky - Web   mobile application development company based in Hong Kong(1)](https://user-images.githubusercontent.com/67095825/91439361-64fd7e00-e89f-11ea-9e02-b0927261261c.png)

**Comment by hochiw** [comment]
@frank-oursky any suggestion on how to style this? simply add a background behind the header? :adore2x:

**Comment by hochiw** [comment]
handled in https://github.com/oursky/oursky-web/commit/7e067a1e86534215597bcd70c72077720ddec423
